# Generated by Django 5.2.2 on 2025-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gospel_images/'),
        ),
        migrations.AddField(
            model_name='sundayinfo',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
